### ISSUE TITLE
Apo-j doesn't save all xforms to paramter file?

### ISSUE THREAD

**Issue by SquirrelMurphy** [mebigfatguy/apophysis-j#1]
Using Apo-J with 64-bit Linux Mint 13 (Ubuntu Precise / 12.04 LTS) and flam3-render. The app generally works properly and renders with flam3 seem to work correctly.

But I have one show stopper: I create a fractal with 5 transforms, Final Transform is disabled (FX button unclicked). I save params. When I look at the param file, there are 2 to 4 xforms in there plus a final xform. The other transforms are missing. I render and I get the wrong image.

If I quit, relaunch, and open the file, It opens with the same wrong image (no surprise) but I notice that Final Transform is enabled. I disable, and my image (and the missing transforms) come back in the Editor. I save, and the same thing happens again. Because flam3 s using the file, it renders incorrectly too. Net result is that I cannot render or save my images. I'm stuck.

I can't use the internal render engine because it throws an error when saving a JPG file. It seems to render properly, but it won't write the file. It writes a file that cannot be opened. Rather than troubleshooting the JPG writing issue, I switched to flam3-render which is nice because it uses all 6 of my cores and is not memory restricted like Apo-J is.

I increased max transforms in options from 2 (the default) to 10 and the save files improved from 2 to 4 transforms... but still don't render properly. Could be a configuration bug, but could be an error too. What could be causing this?

FWIW, launching like this: java -Xmx200m -jar /home/me/Programs/apophysis-j-28/apophysis-j-28.jar

**Comment by mebigfatguy** [comment]
Hi thanks for the report. I believe I've found the problem with the xform counts being wrong. There was a problem in the add and dup controls in the editor not updating the counts. There very well may be other issues in there. This code is very old, and nasty.  I haven't looked at it for a very long while. But hopefully it fixes your issue.

If you find other things feel free to post more issues here. (or if this doesn't fix your issue)..

**Comment by SquirrelMurphy** [comment]
That sounds right. I created 2-3 of 5 transforms, and duplicated the remainder. Thank you for looking at this.
