### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by twobombs** [mebigfatguy/apophysis-j#2]
<img width="1151" alt="screen shot 2017-12-15 at 11 53 39" src="https://user-images.githubusercontent.com/12692227/34039111-ad391e88-e18e-11e7-98cf-dfbb8cdb19a9.png">

after ant build, whilst running java -jar apophysis-j-2.9.0.jar 

weird, no ?

**Comment by mebigfatguy** [comment]
are you using 

ant run

to run it?

Both js.jar, and apophysis-j-plugins-2.9.0.jar need to be on the classpath

**Comment by twobombs** [comment]
tried to run it with java -jar 
ant run works tho, tnx ! :)
